# Manual Back Prop
With the given data that you have at this moment, there are two things that you
should know about , when you are dealing with the given values of the relu, and
you want to minimise the output of that , we are taking those values as one
batch, this is show below :

In [1]:
import numpy as np 
from pprintpp import pprint as pp
dvalues = np.array([[1,1,1],[2,2,2],[3,3,3]])

These values here, are the gradients from the next layer that have been passed
down , its rather easy to see how that works , in this example , ive made it
easy that its only 111 ,222 and so on, but the point for this stands .

the second values is the inputs , these are teh sample data , and not hte
gradient data that we get , or the other values that have been pased from the
next given layer ,

In [2]:
inputs = np.array([[1,2,3,2.5],[2,5,-1,2],[-1.5,2.7,3.3,-0.8]])
pp(inputs)
pp(dvalues)

array([[ 1. ,  2. ,  3. ,  2.5],
       [ 2. ,  5. , -1. ,  2. ],
       [-1.5,  2.7,  3.3, -0.8]])
array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])


Given set of data that we have, nothing more to that  - just data that we are
passing down ,

the dvalues arefixed , as they are teh gradient values , from the next layer ,
to note this values would tend to stay or lean towards just being one

We would then have to pass through the weights, : say that we have 3 sets of
weights : and such that there is one for each given neuron , and because there
are four values , we woud have to transpose tese values such that the shape
matches , shown within, linear algebriac combinations:

In [3]:
weights = np.array(
    [[0.2, 0.8, -0.5, 1], [0.5, -0.91, 0.26, -0.5], [-0.26, -0.27, 0.17, 0.87]]
).T
pp(weights)

array([[ 0.2 ,  0.5 , -0.26],
       [ 0.8 , -0.91, -0.27],
       [-0.5 ,  0.26,  0.17],
       [ 1.  , -0.5 ,  0.87]])


Now we have to define the bias and the layer outputs, with the outsputs, you
should know that it is defined as teh dot product , so that would of been easy
and we are just quickly defining the relu option  : given code shown below

In [4]:
biases = np.array([[2, 3, 0.5]])

layer_outputs = np.dot(inputs, weights) + biases
relu_outputs = np.maximum(0,layer_outputs)

pp([layer_outputs, relu_outputs])

[
    array([[ 4.8  ,  1.21 ,  2.385],
           [ 8.9  , -1.81 ,  0.2  ],
           [ 1.41 ,  1.051,  0.026]]),
    array([[4.8  , 1.21 , 2.385],
           [8.9  , 0.   , 0.2  ],
           [1.41 , 1.051, 0.026]]),
]


Now , the back prop operations would start, or the given values when we are
doing the backwards passs, which ofcours eis the most important pass of the
system


Relu activation, simulates teh dx with respects to teh input value , from teh
next layer passed to teh current layer, this is done during back prop:
Given code is show below :

In [5]:
drelu = relu_outputs.copy()
drelu[relu_outputs <= 0 ] = 0 
pp(drelu)

array([[4.8  , 1.21 , 2.385],
       [8.9  , 0.   , 0.2  ],
       [1.41 , 1.051, 0.026]])


Now we have to deal with teh dense layer, this again is quite straight forward
as this is just using, the dx values that we had  before, but now we are
properly doing the given backwards pass :

In [6]:
print("drelu : \n",drelu,"\n")
print("weights\n", weights,"\n")
print("Weights.T \n",weights.T,"\n")
print("Inputs \n",inputs,"\n")
print("Inputs.T \n",inputs.T,"\n")
dinputs = np.dot(drelu, weights.T)
dweights = np.dot(inputs.T, drelu)

drelu : 
 [[4.8   1.21  2.385]
 [8.9   0.    0.2  ]
 [1.41  1.051 0.026]] 

weights
 [[ 0.2   0.5  -0.26]
 [ 0.8  -0.91 -0.27]
 [-0.5   0.26  0.17]
 [ 1.   -0.5   0.87]] 

Weights.T 
 [[ 0.2   0.8  -0.5   1.  ]
 [ 0.5  -0.91  0.26 -0.5 ]
 [-0.26 -0.27  0.17  0.87]] 

Inputs 
 [[ 1.   2.   3.   2.5]
 [ 2.   5.  -1.   2. ]
 [-1.5  2.7  3.3 -0.8]] 

Inputs.T 
 [[ 1.   2.  -1.5]
 [ 2.   5.   2.7]
 [ 3.  -1.   3.3]
 [ 2.5  2.  -0.8]] 



with the final update of the given code, we would have tofix the dx of inputs
and dx of weights ,, in this case what we are doing is for the inputs , dxinputs
= drelu - all values greater than zero, multiply by the given weights, and this
is quite important  becase partial dx of inputs is teh weights
and the partial dx of weights is  the inputs , so when we are calculating the
given values for the dweights , the shape of the inputs woul dhave to be the
same as teh drelu and once we have that , we should get the folllowing code :

In [7]:
pp([weights, inputs])

dbiases = np.sum(drelu,axis = 0 , keepdims=True)

weights += -0.001 *dweights
biases += -0.001 * dbiases

pp(["Updated Param",weights, biases])

[
    array([[ 0.2 ,  0.5 , -0.26],
           [ 0.8 , -0.91, -0.27],
           [-0.5 ,  0.26,  0.17],
           [ 1.  , -0.5 ,  0.87]]),
    array([[ 1. ,  2. ,  3. ,  2.5],
           [ 2. ,  5. , -1. ,  2. ],
           [-1.5,  2.7,  3.3, -0.8]]),
]
[
    'Updated Param',
    array([[ 0.179515 ,  0.5003665, -0.262746 ],
           [ 0.742093 , -0.9152577, -0.2758402],
           [-0.510153 ,  0.2529017,  0.1629592],
           [ 0.971328 , -0.5021842,  0.8636583]]),
    array([[1.98489 , 2.997739, 0.497389]]),
]
